export enum EnvKeys {
  FAVRO_USER="FAVRO_USER",
  FAVRO_KEY="FAVRO_KEY",
  FAVRO_COMPANY="FAVRO_COMPANY",
  GITLAB_TOKEN = "GITLAB_TOKEN",
  GITLAB_ROOT_BRANCH="GITLAB_ROOT_BRANCH",
  GITLAB_PROJECT_ID="GITLAB_PROJECT_ID",
  GITLAB_API_URL="GITLAB_API_URL"
}